# Generated by Django 2.1.7 on 2023-03-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(max_length=128, null=True, verbose_name='사용자 이메일'),
        ),
    ]
